name: Deploy MSA Libraries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16'
        registry-url: https://registry.npmjs.org/
    - name: install deps and predeploy
      run: |
        yarn
    - name: list 
      run: |
          yarn workspaces since list "HEAD^"
    - name: build 
      run: |
          yarn workspaces since run build "HEAD^"
    - name: version patch
      run: |
          yarn workspaces since run "version patch" "HEAD^"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "[skip ci] version up"
          git push origin main
    - name: deploy 
      env: 
        NPM_AUTH_TOKEN: ${{ secrets.DIVOPS_NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{secrets.DIVOPS_NPM_TOKEN}}
        YARN_NPM_AUTH_TOKEN: ${{secrets.DIVOPS_NPM_TOKEN}}
      run: |
          yarn workspaces since run "npm publish --access public" "HEAD^"