name: Deploy MSA Libraries

on:
  push:
    branches:
      - feat/deploy 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: install deps and predeploy
      run: |
        yarn
    - name: list 
        run: 
          yarn workspaces since list main
    - name: build 
      run: 
          yarn workspaces since run build main
    - name: version patch
      run: 
          yarn workspaces since run version patch main
    - name: deploy 
      env: 
        NPM_AUTH_TOKEN: ${{ secrets.DIVOPS_NPM_TOKEN }}
      run: 
          yarn workspaces since run deploy main